services:
  api:
    image: node:20-slim
    container_name: api
    working_dir: /app

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    env_file: .env
    ports:
      - "4614:4614"

    user: "root"
    command: sh -lc "npm ci && chown -R node:node /app/node_modules && su node -c 'npm run dev'"

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development

volumes:
  node_modules:
